package nerd.utopian.model;

public class BoxOffice {

  private long orderId;
  private String city;
  private Movie movie;

  // region Constructor, getters, setters, equals, hashCode, toString -- generated by BoB the Builder of Beans
  // The code below has been generated by BoB the Builder of Beans based on the class' fields.
  // Everything after this comment will be regenerated if you invoke BoB again.
  // If you don't know who BoB is, you can find him here: https://bitbucket.org/atlassianlabs/bob-the-builder-of-beans

  public BoxOffice(long orderId, String city, Movie movie) {
    this.orderId = orderId;
    this.city = city;
    this.movie = movie;
  }

  // region Getters and setters -- generated by BoB the Builder of Beans
  public long getOrderId() {
    return orderId;
  }

  public void setOrderId(long orderId) {
    this.orderId = orderId;
  }

  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public Movie getMovie() {
    return movie;
  }

  public void setMovie(Movie movie) {
    this.movie = movie;
  }// endregion Getters and setters

  // region hashCode() and equals() -- generated by BoB the Builder of Beans
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    BoxOffice that = (BoxOffice) o;

    if (this.getOrderId() != that.getOrderId()) {
      return false;
    }
    if (this.getCity() != null ? !this.getCity().equals(that.getCity()) : that.getCity() != null) {
      return false;
    }
    if (this.getMovie() != null ? !this.getMovie().equals(that.getMovie())
        : that.getMovie() != null) {
      return false;
    }
    return true;
  }

  @Override
  public int hashCode() {
    int result = Long.valueOf(getOrderId()).hashCode();
    result = 31 * result + (getCity() != null ? getCity().hashCode() : 0);
    result = 31 * result + (getMovie() != null ? getMovie().hashCode() : 0);
    return result;
  }// endregion hashCode() and equals()

  // region toString() -- generated by BoB the Builder of Beans
  @Override
  public String toString() {
    return "BoxOffice{" +
        "orderId=" + getOrderId() +
        ", city=" + getCity() +
        ", movie=" + getMovie() +
        "}";
  }// endregion toString()
  // endregion Constructor, getters, setters, equals, hashCode, toString
}
