package nerd.utopian.model;

import java.util.Objects;
import java.util.StringJoiner;

public class IngestionResponse {

  private String ingestionResult;
  private IngestionRequest ingestionRequest;

  // region Constructor, getters, setters, equals, hashCode, toString -- generated by BoB the Builder of Beans
  // The code below has been generated by BoB the Builder of Beans based on the class' fields.
  // Everything after this comment will be regenerated if you invoke BoB again.
  // If you don't know who BoB is, you can find him here: https://bitbucket.org/atlassianlabs/bob-the-builder-of-beans

  public IngestionResponse(String ingestionResult, IngestionRequest ingestionRequest) {
    this.ingestionResult = Objects.requireNonNull(ingestionResult);
    this.ingestionRequest = Objects.requireNonNull(ingestionRequest);
  }

  // region Getters and setters -- generated by BoB the Builder of Beans
  public String getIngestionResult() {
    return ingestionResult;
  }

  public void setIngestionResult(String ingestionResult) {
    this.ingestionResult = Objects.requireNonNull(ingestionResult);
  }

  public IngestionRequest getIngestionRequest() {
    return ingestionRequest;
  }

  public void setIngestionRequest(IngestionRequest ingestionRequest) {
    this.ingestionRequest = Objects.requireNonNull(ingestionRequest);
  }// endregion Getters and setters

  // region hashCode() and equals() -- generated by BoB the Builder of Beans
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    IngestionResponse that = (IngestionResponse) o;

    return Objects.equals(this.getIngestionResult(), that.getIngestionResult()) && Objects.equals(
        this.getIngestionRequest(), that.getIngestionRequest());
  }

  @Override
  public int hashCode() {
    return Objects.hash(getIngestionResult(), getIngestionRequest());
  }// endregion hashCode() and equals()

  // region toString() -- generated by BoB the Builder of Beans
  @Override
  public String toString() {
    return new StringJoiner(", ", this.getClass().getSimpleName() + "{", "}")
        .add("ingestionResult=" + getIngestionResult())
        .add("ingestionRequest=" + getIngestionRequest())
        .toString();
  }// endregion toString()
  // endregion Constructor, getters, setters, equals, hashCode, toString
}
