package nerd.utopian.model;

public class Movie {

  private long movieId;
  private String movieName;

  // region Constructor, getters, setters, equals, hashCode, toString -- generated by BoB the Builder of Beans
  // The code below has been generated by BoB the Builder of Beans based on the class' fields.
  // Everything after this comment will be regenerated if you invoke BoB again.
  // If you don't know who BoB is, you can find him here: https://bitbucket.org/atlassianlabs/bob-the-builder-of-beans

  public Movie(long movieId, String movieName) {
    this.movieId = movieId;
    this.movieName = movieName;
  }

  // region Getters and setters -- generated by BoB the Builder of Beans
  public long getMovieId() {
    return movieId;
  }

  public void setMovieId(long movieId) {
    this.movieId = movieId;
  }

  public String getMovieName() {
    return movieName;
  }

  public void setMovieName(String movieName) {
    this.movieName = movieName;
  }// endregion Getters and setters

  // region hashCode() and equals() -- generated by BoB the Builder of Beans
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    Movie that = (Movie) o;

    if (this.getMovieId() != that.getMovieId()) {
      return false;
    }
    if (this.getMovieName() != null ? !this.getMovieName().equals(that.getMovieName())
        : that.getMovieName() != null) {
      return false;
    }
    return true;
  }

  @Override
  public int hashCode() {
    int result = Long.valueOf(getMovieId()).hashCode();
    result = 31 * result + (getMovieName() != null ? getMovieName().hashCode() : 0);
    return result;
  }// endregion hashCode() and equals()

  // region toString() -- generated by BoB the Builder of Beans
  @Override
  public String toString() {
    return "Movie{" +
        "movieId=" + getMovieId() +
        ", movieName=" + getMovieName() +
        "}";
  }// endregion toString()
  // endregion Constructor, getters, setters, equals, hashCode, toString
}
